# Generated by Django 2.0.4 on 2018-05-01 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0002_sessioncart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session_cart',
            name='books',
        ),
        migrations.RemoveField(
            model_name='session_cart',
            name='user',
        ),
        migrations.DeleteModel(
            name='Session_Cart',
        ),
    ]
