# Generated by Django 2.0.4 on 2018-04-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateTimeField(blank=True, null=True, verbose_name='date of birth')),
                ('date_of_death', models.DateTimeField(blank=True, null=True, verbose_name='date of death')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(blank=True, null=True, verbose_name='date published')),
                ('synopsis', models.TextField(blank=True, max_length=2500)),
                ('path_to_img', models.CharField(max_length=260)),
                ('buy_price', models.FloatField(blank=True, null=True)),
                ('rent_price', models.FloatField(blank=True, null=True)),
                ('author_names', models.ManyToManyField(to='books.Author', verbose_name='Author')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=30, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(to='books.Genre', verbose_name='Genre'),
        ),
    ]
