# Generated by Django 2.0.4 on 2018-04-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre_name',
            field=models.CharField(default='', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
