# Generated by Django 2.0.4 on 2018-05-01 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20180430_2219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author_names',
            new_name='authors',
        ),
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.DateField(blank=True, null=True, verbose_name='date published'),
        ),
    ]
